### ISSUE TITLE
GCodes generated by OrcaSlicer go in Error when using ColorMode = Feature

### ISSUE THREAD

**Issue by TopoDiFogna** [Sindarius/npm_gcodeviewer#12]
Issue originally opened in mainsail https://github.com/mainsail-crew/mainsail/issues/1752 still reproducible with latest version (3.7.6 when writing this) and visible also @ https://sindarius.com/
Sample File:  [Sovol SV06 Filament Runout Sensor Mount_PLA_30m48s.zip](https://github.com/Sindarius/npm_gcodeviewer/files/14318427/Sovol.SV06.Filament.Runout.Sensor.Mount_PLA_30m48s.zip)

**Comment by Sindarius** [comment]
Implemented code changes to resolve this issue with a default unknown to prevent unknown variable. Also added the two missing feature colors to OrcaSlicer.
